name: VorplexTownyCore
author: I54m
website: https://i54m.com
version: 1.0
main: com.i54m.vorplextownycore.Main
description: A plugin to add a richest town and richest nation stat to LeaderHeads and plot vouchers.
api-version: 1.16
softdepend:
  - MVdWPlaceholdeAPI
  - AlonsoLeaderboards
  - Towny

commands:
  giveplotvouchers:
    description: give a player plot vouchers.


permissions:
  vorplexcore.townyplotvouchers.give:
    description: allows the player to use the give plot vouchers command.
    default: op